'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("inoHotKeys.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property cmdCancel() As String
            Get
                Return ResourceManager.GetString("cmdCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property cmdOK() As String
            Get
                Return ResourceManager.GetString("cmdOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property cmdSave() As String
            Get
                Return ResourceManager.GetString("cmdSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainAbout() As String
            Get
                Return ResourceManager.GetString("MainAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Arrage icons ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainArrageIcons() As String
            Get
                Return ResourceManager.GetString("MainArrageIcons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cascading ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainCascading() As String
            Get
                Return ResourceManager.GetString("MainCascading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Close all ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainCloseAll() As String
            Get
                Return ResourceManager.GetString("MainCloseAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainExit() As String
            Get
                Return ResourceManager.GetString("MainExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainFile() As String
            Get
                Return ResourceManager.GetString("MainFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainHelp() As String
            Get
                Return ResourceManager.GetString("MainHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New Windows ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainNewWindows() As String
            Get
                Return ResourceManager.GetString("MainNewWindows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainOpen() As String
            Get
                Return ResourceManager.GetString("MainOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainOptions() As String
            Get
                Return ResourceManager.GetString("MainOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Shortcut Settings ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainShortcutSettings() As String
            Get
                Return ResourceManager.GetString("MainShortcutSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tile horizontal ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainTileHorizontal() As String
            Get
                Return ResourceManager.GetString("MainTileHorizontal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tile vertical ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainTileVertical() As String
            Get
                Return ResourceManager.GetString("MainTileVertical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainTools() As String
            Get
                Return ResourceManager.GetString("MainTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Windows ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainWindows() As String
            Get
                Return ResourceManager.GetString("MainWindows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Autostart Application with Windows start ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property OptionAutostart() As String
            Get
                Return ResourceManager.GetString("OptionAutostart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property OptionLanguage() As String
            Get
                Return ResourceManager.GetString("OptionLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die To apply the language settings the application needs to be restarted. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property OptionMessageLanguageChange() As String
            Get
                Return ResourceManager.GetString("OptionMessageLanguageChange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property OptionTitel() As String
            Get
                Return ResourceManager.GetString("OptionTitel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New Outlook email ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShortcutNewOutlookEmail() As String
            Get
                Return ResourceManager.GetString("ShortcutNewOutlookEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Send Windows to sleep ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShortcutSendToSleep() As String
            Get
                Return ResourceManager.GetString("ShortcutSendToSleep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Action ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShortSetAction() As String
            Get
                Return ResourceManager.GetString("ShortSetAction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Activated ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShortSetActivated() As String
            Get
                Return ResourceManager.GetString("ShortSetActivated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alt ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShortSetAlt() As String
            Get
                Return ResourceManager.GetString("ShortSetAlt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Shortcut Settings ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShortSetCaption() As String
            Get
                Return ResourceManager.GetString("ShortSetCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ctrl ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShortSetCrtl() As String
            Get
                Return ResourceManager.GetString("ShortSetCrtl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Key ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShortSetKey() As String
            Get
                Return ResourceManager.GetString("ShortSetKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You need to select at least one modifier key for the hot key &apos;{0}&apos;. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShortSetMessage1() As String
            Get
                Return ResourceManager.GetString("ShortSetMessage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The changes will not be saved. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShortSetMessage2() As String
            Get
                Return ResourceManager.GetString("ShortSetMessage2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hotkey not available as MS Outlook is not installed. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShortSetMsgOutlookMissing() As String
            Get
                Return ResourceManager.GetString("ShortSetMsgOutlookMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Shift ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShortSetShift() As String
            Get
                Return ResourceManager.GetString("ShortSetShift", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Win ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShortSetWin() As String
            Get
                Return ResourceManager.GetString("ShortSetWin", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
